import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'webhooks/index': 'src/webhooks/index.ts',
    'events/index': 'src/events/index.ts',
    'state-machine/index': 'src/state-machine/index.ts',
    'plans/index': 'src/plans/index.ts',
    'idempotency/index': 'src/idempotency/index.ts',
    'errors/index': 'src/errors/index.ts',
    'adapters/next/index': 'src/adapters/next/index.ts',
    'adapters/hono/index': 'src/adapters/hono/index.ts',
    'adapters/fastify/index': 'src/adapters/fastify/index.ts',
    'adapters/express/index': 'src/adapters/express/index.ts',
    'adapters/sveltekit/index': 'src/adapters/sveltekit/index.ts',
    'adapters/nitro/index': 'src/adapters/nitro/index.ts',
    'storage/memory/index': 'src/storage/memory/index.ts',
    'storage/redis/index': 'src/storage/redis/index.ts',
    'storage/kv/index': 'src/storage/kv/index.ts',
    'storage/durable-objects/index': 'src/storage/durable-objects/index.ts',
    'storage/postgres/index': 'src/storage/postgres/index.ts',
    'testing/index': 'src/testing/index.ts',
    'testing/fixtures/index': 'src/testing/fixtures/index.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: false,
  treeshake: true,
  sourcemap: true,
  clean: true,
  target: 'es2022',
  platform: 'neutral',
  outDir: 'dist',
});
